FROM openmedicus/centos-lamp:7.1
MAINTAINER Mikkel Kruse Johnsen <mikkel@xmedicus.com>

RUN echo $'\n\ndate.timezone = "Europe/Copenhagen"' >> /etc/php.ini

ADD mantisbt-@VERSION@.tar.gz /
RUN mv mantisbt-@VERSION@/* /var/www/html/

ADD parsedown-master.zip /
RUN unzip parsedown-master.zip
RUN mv parsedown-master /var/www/html/library/parsedown

RUN chown -R apache:apache /var/www/html

